name: release-please

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.6.1)'
        required: false
        type: string
  push:
    tags:
      - 'v*'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          package-name: harvester-ui-extension
          path: pkg/harvester
          version: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix changelog authors
        run: node scripts/fix-authors.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }} 